// Generated by jextract

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor echo$FUNC = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("message"),
            Constants$root.C_INT$LAYOUT.withName("repeat"),
            MemoryLayout.paddingLayout(32)
        ).withName("Echo")
    );
    static final MethodHandle echo$MH = RuntimeHelper.downcallHandle(
        "echo",
        constants$0.echo$FUNC, false
    );
}


