// Generated by jextract

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class Echo {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("message"),
        Constants$root.C_INT$LAYOUT.withName("repeat"),
        MemoryLayout.paddingLayout(32)
    ).withName("Echo");
    public static MemoryLayout $LAYOUT() {
        return Echo.$struct$LAYOUT;
    }
    static final VarHandle message$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("message"));
    public static VarHandle message$VH() {
        return Echo.message$VH;
    }
    public static MemoryAddress message$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)Echo.message$VH.get(seg);
    }
    public static void message$set( MemorySegment seg, MemoryAddress x) {
        Echo.message$VH.set(seg, x);
    }
    public static MemoryAddress message$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)Echo.message$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void message$set(MemorySegment seg, long index, MemoryAddress x) {
        Echo.message$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle repeat$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("repeat"));
    public static VarHandle repeat$VH() {
        return Echo.repeat$VH;
    }
    public static int repeat$get(MemorySegment seg) {
        return (int)Echo.repeat$VH.get(seg);
    }
    public static void repeat$set( MemorySegment seg, int x) {
        Echo.repeat$VH.set(seg, x);
    }
    public static int repeat$get(MemorySegment seg, long index) {
        return (int)Echo.repeat$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void repeat$set(MemorySegment seg, long index, int x) {
        Echo.repeat$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


