// Generated by jextract

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor helloworld$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle helloworld$MH = RuntimeHelper.downcallHandle(
        "helloworld",
        constants$0.helloworld$FUNC, false
    );
}


